/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import db.PerguntaCompletaDAO;
import db.PerguntaDAO;
import javax.swing.JOptionPane;
import modelo.Jogador;
import static telas.PerguntaTela.MAX_PERGUNTAS_POR_PARTIDA;

/**
 *
 * @author Matheus
 */
public class EscolhaDoNomeTela extends javax.swing.JFrame {

  /**
   * Creates new form EscolhaDoNomeTela
   */
  public EscolhaDoNomeTela() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    fundoEscolhaDoNomeTela = new javax.swing.JPanel();
    retanguloBaseEscolhaNomePanel = new javax.swing.JPanel();
    textoEscolhaNomeLabel = new javax.swing.JLabel();
    escolhaDoNomeTextField = new javax.swing.JTextField();
    confirmarButton = new javax.swing.JButton();
    voltarButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setSize(new java.awt.Dimension(1280, 720));

    fundoEscolhaDoNomeTela.setBackground(new java.awt.Color(56, 56, 56));
    fundoEscolhaDoNomeTela.setMaximumSize(new java.awt.Dimension(1280, 720));
    fundoEscolhaDoNomeTela.setMinimumSize(new java.awt.Dimension(1280, 720));

    retanguloBaseEscolhaNomePanel.setBackground(new java.awt.Color(126, 126, 126));
    retanguloBaseEscolhaNomePanel.setMaximumSize(new java.awt.Dimension(600, 300));
    retanguloBaseEscolhaNomePanel.setMinimumSize(new java.awt.Dimension(600, 300));
    retanguloBaseEscolhaNomePanel.setPreferredSize(new java.awt.Dimension(600, 300));

    textoEscolhaNomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
    textoEscolhaNomeLabel.setForeground(new java.awt.Color(255, 255, 255));
    textoEscolhaNomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    textoEscolhaNomeLabel.setText("Escolha um nome para jogar");

    escolhaDoNomeTextField.setBackground(new java.awt.Color(55, 55, 55));
    escolhaDoNomeTextField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
    escolhaDoNomeTextField.setForeground(new java.awt.Color(255, 255, 255));

    confirmarButton.setBackground(new java.awt.Color(51, 51, 51));
    confirmarButton.setForeground(new java.awt.Color(255, 255, 255));
    confirmarButton.setText("Confirmar");
    confirmarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirmarButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout retanguloBaseEscolhaNomePanelLayout = new javax.swing.GroupLayout(retanguloBaseEscolhaNomePanel);
    retanguloBaseEscolhaNomePanel.setLayout(retanguloBaseEscolhaNomePanelLayout);
    retanguloBaseEscolhaNomePanelLayout.setHorizontalGroup(
      retanguloBaseEscolhaNomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(textoEscolhaNomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, retanguloBaseEscolhaNomePanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(escolhaDoNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(160, 160, 160))
      .addGroup(retanguloBaseEscolhaNomePanelLayout.createSequentialGroup()
        .addGap(240, 240, 240)
        .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(240, 240, 240))
    );
    retanguloBaseEscolhaNomePanelLayout.setVerticalGroup(
      retanguloBaseEscolhaNomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(retanguloBaseEscolhaNomePanelLayout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(textoEscolhaNomeLabel)
        .addGap(64, 64, 64)
        .addComponent(escolhaDoNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
        .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(35, 35, 35))
    );

    voltarButton.setBackground(new java.awt.Color(100, 100, 100));
    voltarButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
    voltarButton.setForeground(new java.awt.Color(255, 255, 255));
    voltarButton.setText("Voltar");
    voltarButton.setMaximumSize(new java.awt.Dimension(90, 40));
    voltarButton.setMinimumSize(new java.awt.Dimension(90, 40));
    voltarButton.setPreferredSize(new java.awt.Dimension(90, 40));
    voltarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        voltarButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout fundoEscolhaDoNomeTelaLayout = new javax.swing.GroupLayout(fundoEscolhaDoNomeTela);
    fundoEscolhaDoNomeTela.setLayout(fundoEscolhaDoNomeTelaLayout);
    fundoEscolhaDoNomeTelaLayout.setHorizontalGroup(
      fundoEscolhaDoNomeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(fundoEscolhaDoNomeTelaLayout.createSequentialGroup()
        .addGroup(fundoEscolhaDoNomeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(fundoEscolhaDoNomeTelaLayout.createSequentialGroup()
            .addGap(340, 340, 340)
            .addComponent(retanguloBaseEscolhaNomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(fundoEscolhaDoNomeTelaLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(340, Short.MAX_VALUE))
    );
    fundoEscolhaDoNomeTelaLayout.setVerticalGroup(
      fundoEscolhaDoNomeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(fundoEscolhaDoNomeTelaLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(152, 152, 152)
        .addComponent(retanguloBaseEscolhaNomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(210, 210, 210))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(fundoEscolhaDoNomeTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(fundoEscolhaDoNomeTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
    // TODO add your handling code here:
    var ti = new InicialTela();
    ti.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_voltarButtonActionPerformed

  private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
    String nomeDeJogo = escolhaDoNomeTextField.getText();
    if(nomeDeJogo.isEmpty())
      JOptionPane.showMessageDialog(null, "Escolha um nome de jogo", "Erro", 0);
    else
    {
      try
      {
        var dao = new PerguntaDAO();
        if(dao.numeroDePerguntas() < MAX_PERGUNTAS_POR_PARTIDA)
        {
          JOptionPane.showMessageDialog(null, "Não há perguntas cadastradas o suficiente para jogar", "Erro", 0);
        }
        else
        {
          var dao2 = new PerguntaCompletaDAO();
          var perguntas = dao2.obterPerguntasParaJogar();
          var j = new Jogador(nomeDeJogo);
          var tp = new PerguntaTela(j, 1, perguntas);
          tp.setVisible(true);
          this.dispose();
        }
      }
      catch(Exception e)
      {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
      }
    }
  }//GEN-LAST:event_confirmarButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EscolhaDoNomeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EscolhaDoNomeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EscolhaDoNomeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EscolhaDoNomeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new EscolhaDoNomeTela().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton confirmarButton;
  private javax.swing.JTextField escolhaDoNomeTextField;
  private javax.swing.JPanel fundoEscolhaDoNomeTela;
  private javax.swing.JPanel retanguloBaseEscolhaNomePanel;
  private javax.swing.JLabel textoEscolhaNomeLabel;
  private javax.swing.JButton voltarButton;
  // End of variables declaration//GEN-END:variables
}
