/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Matheus
 */
public class InicialTela extends javax.swing.JFrame {
  private int idUsuarioLogado;

  /**
   * Creates new form TelaTeste
   */
  public InicialTela() {
    initComponents();
    setLocationRelativeTo(null);
  }
  
  public InicialTela(int idUsuarioLogado) {
    initComponents();
    setLocationRelativeTo(null);
    this.idUsuarioLogado = idUsuarioLogado;
  }

  public int getIdUsuarioLogado() {
    return idUsuarioLogado;
  }

  public void setIdUsuarioLogado(int idUsuarioLogado) {
    this.idUsuarioLogado = idUsuarioLogado;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    fundoTelaInicialPanel = new javax.swing.JPanel();
    tituloDoJogoLabel = new javax.swing.JLabel();
    rankingButton = new javax.swing.JButton();
    loginButton = new javax.swing.JButton();
    sairButton = new javax.swing.JButton();
    jogarButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));

    fundoTelaInicialPanel.setBackground(new java.awt.Color(56, 56, 56));
    fundoTelaInicialPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
    fundoTelaInicialPanel.setMinimumSize(new java.awt.Dimension(1280, 720));

    tituloDoJogoLabel.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
    tituloDoJogoLabel.setForeground(new java.awt.Color(255, 255, 255));
    tituloDoJogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    tituloDoJogoLabel.setText("QUIZ CITOLOGIA");

    rankingButton.setBackground(new java.awt.Color(80, 80, 80));
    rankingButton.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
    rankingButton.setForeground(new java.awt.Color(255, 255, 255));
    rankingButton.setText("Ranking");
    rankingButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rankingButtonActionPerformed(evt);
      }
    });

    loginButton.setBackground(new java.awt.Color(80, 80, 80));
    loginButton.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
    loginButton.setForeground(new java.awt.Color(255, 255, 255));
    loginButton.setText("Login");
    loginButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginButtonActionPerformed(evt);
      }
    });

    sairButton.setBackground(new java.awt.Color(80, 80, 80));
    sairButton.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
    sairButton.setForeground(new java.awt.Color(255, 255, 255));
    sairButton.setText("Sair");
    sairButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sairButtonActionPerformed(evt);
      }
    });

    jogarButton.setBackground(new java.awt.Color(80, 80, 80));
    jogarButton.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
    jogarButton.setForeground(new java.awt.Color(255, 255, 255));
    jogarButton.setText("Jogar");
    jogarButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jogarButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout fundoTelaInicialPanelLayout = new javax.swing.GroupLayout(fundoTelaInicialPanel);
    fundoTelaInicialPanel.setLayout(fundoTelaInicialPanelLayout);
    fundoTelaInicialPanelLayout.setHorizontalGroup(
      fundoTelaInicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tituloDoJogoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoTelaInicialPanelLayout.createSequentialGroup()
        .addContainerGap(534, Short.MAX_VALUE)
        .addGroup(fundoTelaInicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jogarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(rankingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(534, 534, 534))
    );
    fundoTelaInicialPanelLayout.setVerticalGroup(
      fundoTelaInicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(fundoTelaInicialPanelLayout.createSequentialGroup()
        .addGap(44, 44, 44)
        .addComponent(tituloDoJogoLabel)
        .addGap(104, 104, 104)
        .addComponent(jogarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(rankingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(165, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(fundoTelaInicialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(fundoTelaInicialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jogarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarButtonActionPerformed
    // TODO add your handling code here:
    var tedn = new EscolhaDoNomeTela();
    tedn.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_jogarButtonActionPerformed

  private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
    // TODO add your handling code here:
    dispose();
  }//GEN-LAST:event_sairButtonActionPerformed

  private void rankingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingButtonActionPerformed
    // TODO add your handling code here:
    var telaRanking = new RankingTela();
    telaRanking.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_rankingButtonActionPerformed

  private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    // TODO add your handling code here:
    var telaLogin = new LoginTela();
    telaLogin.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_loginButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(InicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(InicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(InicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(InicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new InicialTela().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel fundoTelaInicialPanel;
  private javax.swing.JButton jogarButton;
  private javax.swing.JButton loginButton;
  private javax.swing.JButton rankingButton;
  private javax.swing.JButton sairButton;
  private javax.swing.JLabel tituloDoJogoLabel;
  // End of variables declaration//GEN-END:variables
}
