/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Matheus
 */
public class PerguntaTela extends javax.swing.JFrame {

  /**
   * Creates new form PerguntaTela
   */
  public PerguntaTela() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    fundoTelaPerguntaPanel = new javax.swing.JPanel();
    enunciadoLabel = new javax.swing.JLabel();
    alt2Button = new javax.swing.JButton();
    alt3Button = new javax.swing.JButton();
    alt4Button = new javax.swing.JButton();
    alt1Button = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setSize(new java.awt.Dimension(1280, 720));

    fundoTelaPerguntaPanel.setBackground(new java.awt.Color(56, 56, 56));
    fundoTelaPerguntaPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
    fundoTelaPerguntaPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
    fundoTelaPerguntaPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
    fundoTelaPerguntaPanel.setRequestFocusEnabled(false);

    enunciadoLabel.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
    enunciadoLabel.setForeground(new java.awt.Color(255, 255, 255));
    enunciadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    enunciadoLabel.setText("ENUNCIADO");

    alt2Button.setBackground(new java.awt.Color(80, 80, 80));
    alt2Button.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
    alt2Button.setForeground(new java.awt.Color(255, 255, 255));
    alt2Button.setText("Alternativa 2");
    alt2Button.setMaximumSize(new java.awt.Dimension(270, 120));
    alt2Button.setMinimumSize(new java.awt.Dimension(270, 120));
    alt2Button.setPreferredSize(new java.awt.Dimension(270, 120));

    alt3Button.setBackground(new java.awt.Color(80, 80, 80));
    alt3Button.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
    alt3Button.setForeground(new java.awt.Color(255, 255, 255));
    alt3Button.setText("Alternativa 3");
    alt3Button.setMaximumSize(new java.awt.Dimension(270, 120));
    alt3Button.setMinimumSize(new java.awt.Dimension(270, 120));
    alt3Button.setPreferredSize(new java.awt.Dimension(270, 120));

    alt4Button.setBackground(new java.awt.Color(80, 80, 80));
    alt4Button.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
    alt4Button.setForeground(new java.awt.Color(255, 255, 255));
    alt4Button.setText("Alternativa4");
    alt4Button.setMaximumSize(new java.awt.Dimension(270, 120));
    alt4Button.setMinimumSize(new java.awt.Dimension(270, 120));
    alt4Button.setPreferredSize(new java.awt.Dimension(270, 120));

    alt1Button.setBackground(new java.awt.Color(80, 80, 80));
    alt1Button.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
    alt1Button.setForeground(new java.awt.Color(255, 255, 255));
    alt1Button.setText("Alternativa 1");
    alt1Button.setMaximumSize(new java.awt.Dimension(270, 120));
    alt1Button.setMinimumSize(new java.awt.Dimension(270, 120));
    alt1Button.setPreferredSize(new java.awt.Dimension(270, 120));

    jTextField1.setEditable(false);
    jTextField1.setBackground(new java.awt.Color(140, 140, 140));
    jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(255, 255, 255));
    jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jTextField1.setText("13");
    jTextField1.setBorder(null);
    jTextField1.setMaximumSize(new java.awt.Dimension(70, 70));
    jTextField1.setMinimumSize(new java.awt.Dimension(70, 70));
    jTextField1.setPreferredSize(new java.awt.Dimension(70, 70));

    javax.swing.GroupLayout fundoTelaPerguntaPanelLayout = new javax.swing.GroupLayout(fundoTelaPerguntaPanel);
    fundoTelaPerguntaPanel.setLayout(fundoTelaPerguntaPanelLayout);
    fundoTelaPerguntaPanelLayout.setHorizontalGroup(
      fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(enunciadoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(fundoTelaPerguntaPanelLayout.createSequentialGroup()
        .addGroup(fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(fundoTelaPerguntaPanelLayout.createSequentialGroup()
            .addGap(290, 290, 290)
            .addGroup(fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(alt3Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(alt1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(160, 160, 160)
            .addGroup(fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(alt2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(alt4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(fundoTelaPerguntaPanelLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(290, Short.MAX_VALUE))
    );
    fundoTelaPerguntaPanelLayout.setVerticalGroup(
      fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(fundoTelaPerguntaPanelLayout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(enunciadoLabel)
        .addGap(120, 120, 120)
        .addGroup(fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(alt2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(alt1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(76, 76, 76)
        .addGroup(fundoTelaPerguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(alt3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(alt4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(86, 86, 86))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(fundoTelaPerguntaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(fundoTelaPerguntaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(PerguntaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(PerguntaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(PerguntaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(PerguntaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PerguntaTela().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton alt1Button;
  private javax.swing.JButton alt2Button;
  private javax.swing.JButton alt3Button;
  private javax.swing.JButton alt4Button;
  private javax.swing.JLabel enunciadoLabel;
  private javax.swing.JPanel fundoTelaPerguntaPanel;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
